name: Manual Trigger Workflow

# configure manual trigger
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
     # - name: Configure AWS credentials
       #uses: aws-actions/configure-aws-credentials@v1
        #with:
          #role-to-assume: arn:aws:iam::450683952831:role/AWSControlTowerExecution
          #aws-region: eu-central-1
      #- uses: mcblair/configure-aws-profile-action@v0.1.1
      #  with:
       #   role-arn: arn:aws:iam::450683952831:role/AWSControlTowerExecution
       #   profile-name: test
        
      - name: Terraform validate
        working-directory: ./terraform-modules/cur-setup-destination
        run: | 
          terraform init
          terraform validate 
        shell: bash
    
      - name: Terraform plan
        working-directory: ./terraform/cur-setup-destination
        run: terraform plan
       
      
           
