name: Manual Trigger Workflow

# configure manual trigger
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::450683952831:role/AWSControlTowerExecution
          aws-region: eu-central-1
        
      - name: Terraform validate
        working-directory: ./terraform-modules/cur-setup-destination
        run: | 
          terraform init
          terraform validate 
        shell: bash
    
      - name: Terraform plan
        working-directory: ./terraform/cur-setup-destination
        run: terraform plan
       
      
           
